TestFramework:RegisterTest("[Transaction] should return added queries correctly", function(test)
	local db = TestFramework:ConnectToDatabase()
	local q1 = db:query("SELECT 1")
	local q2 = db:prepare("SELECT ?")
	q2:setNumber(2, 2)
	local q3 = db:query("SELECT 3")
	local transaction = db:createTransaction()
	test:shouldHaveLength(transaction:getQueries(), 0)
	transaction:addQuery(q1)
	transaction:addQuery(q2)
	transaction:addQuery(q3)
	local queries = transaction:getQueries()
	test:shouldHaveLength(transaction:getQueries(), 3)
	test:shouldBeEqual(queries[1], q1)
	test:shouldBeEqual(queries[2], q2)
	test:shouldBeEqual(queries[3], q3)
	test:Complete()
end)

TestFramework:RegisterTest("[Transaction] run transaction with same query correctly", function(test)
	local db = TestFramework:ConnectToDatabase()
	local transaction = db:createTransaction()
	local qu = db:prepare("SELECT ? as a")
	qu:setNumber(1, 1)
	transaction:addQuery(qu)
	qu:setNumber(1, 3)
	transaction:addQuery(qu)
	function transaction:onSuccess(data)
		test:shouldHaveLength(data, 2)
		test:shouldBeEqual(data[1][1].a, 1)
		test:shouldBeEqual(data[2][1].a, 3)
		test:Complete()
	end
	transaction:start()
	transaction:wait()
end)

TestFramework:RegisterTest("[Transaction] rollback query status", function(test)
	local db = TestFramework:ConnectToDatabase()
	local transaction = db:createTransaction()
	local qu = db:query("select * * * fom abc")
	local qu2 = db:query("SELECT 1")
	transaction:addQuery(qu)
	transaction:addQuery(qu2)
	function transaction:onError()
		test:shouldNotBeEqual(qu:error(), "")
		test:shouldBeEqual(qu2:error(), "")

		test:shouldBeEqual(qu:isRunning(), true)
		test:shouldBeEqual(qu2:isRunning(), true)
		test:shouldBeEqual(transaction:isRunning(), true)

		test:shouldBeEqual(qu:hasMoreResults(), false)
		test:shouldBeEqual(qu2:hasMoreResults(), false)

		timer.Simple(0.1, function()
			test:shouldBeEqual(qu:isRunning(), false)
			test:shouldBeEqual(qu2:isRunning(), false)
			test:shouldBeEqual(transaction:isRunning(), false)
			test:Complete()
		end)
	end
	transaction:start()
end)



TestFramework:RegisterTest("[Transaction] work with multiple result sets", function(test)
	local db = TestFramework:ConnectToDatabase()
	local transaction = db:createTransaction()
	local qu1 = db:query("SELECT 1 as a; SELECT 2 as b;")
	local qu2 = db:query("SELECT 3 as a")
	transaction:addQuery(qu1)
	transaction:addQuery(qu2)
	function transaction:onSuccess(data)
		test:shouldHaveLength(data, 2)
		test:shouldBeEqual(data[1][1].a, 1)
		test:shouldBeEqual(data[2][1].a, 3)

		test:shouldBeEqual(qu1:hasMoreResults(), true)
		test:shouldBeEqual(qu2:hasMoreResults(), true)

		qu1:getNextResults()
		qu2:getNextResults()

		test:shouldBeEqual(qu1:hasMoreResults(), true)
		test:shouldBeEqual(qu2:hasMoreResults(), false)

		qu1:getNextResults()
		test:shouldBeEqual(qu1:hasMoreResults(), false)

		test:Complete()
	end
	transaction:start()
	transaction:wait()
end)

TestFramework:RegisterTest("[Transaction] abort queries correctly", function(test)
	local db = TestFramework:ConnectToDatabase()
	local transaction = db:createTransaction()
	local qu = db:query("SELECT SLEEP(1)")
	qu:start()
	local qu1 = db:query("SELECT 1")
	local qu2 = db:query("SELECT 2")
	transaction:addQuery(qu1)
	transaction:addQuery(qu2)
	function transaction:onAborted()
		test:shouldBeEqual(qu1:isRunning(), true)
		test:shouldBeEqual(qu2:isRunning(), true)

		timer.Simple(0.1, function()
			test:shouldBeEqual(qu1:isRunning(), false)
			test:shouldBeEqual(qu2:isRunning(), false)
			test:Complete()
		end)
	end
	transaction:start()
	test:shouldBeEqual(transaction:abort(), true)
end)

TestFramework:RegisterTest("[Transaction] abort queries correctly through abortAll", function(test)
	local db = TestFramework:ConnectToDatabase()
	local transaction = db:createTransaction()
	local qu = db:query("SELECT SLEEP(1)")
	qu:start()
	local qu1 = db:query("SELECT 1")
	local qu2 = db:query("SELECT 2")
	transaction:addQuery(qu1)
	transaction:addQuery(qu2)
	function transaction:onAborted()
		test:shouldBeEqual(qu1:isRunning(), true)
		test:shouldBeEqual(qu2:isRunning(), true)

		timer.Simple(0.1, function()
			test:shouldBeEqual(qu1:isRunning(), false)
			test:shouldBeEqual(qu2:isRunning(), false)
			test:Complete()
		end)
	end
	transaction:start()
	local amountAborted = db:abortAllQueries()
	test:shouldBeGreaterThan(amountAborted, 0)
end)

TestFramework:RegisterTest("[Transaction] return correct data for queries executed before an error happened", function(test)
	local db = TestFramework:ConnectToDatabase()
	local transaction = db:createTransaction()
	local qu = db:query("SELECT 123 as a")
	local qu1 = db:query("SELECT 'test' as b")
	local qu2 = db:query("SELECT * * * * * *")
	local qu3 = db:query("SELECT 3")
	transaction:addQuery(qu)
	transaction:addQuery(qu1)
	transaction:addQuery(qu2)
	transaction:addQuery(qu3)
	function transaction:onError()
		test:shouldBeEqual(qu:isRunning(), true)
		test:shouldBeEqual(qu1:isRunning(), true)
		test:shouldBeEqual(qu2:isRunning(), true)
		test:shouldBeEqual(qu3:isRunning(), true)

		test:shouldBeEqual(qu:error(), "")
		test:shouldBeEqual(qu1:error(), "")
		test:shouldNotBeEqual(qu2:error(), "")
		test:shouldBeEqual(qu3:error(), "")

		test:shouldBeEqual(qu:hasMoreResults(), true)
		test:shouldBeEqual(qu1:hasMoreResults(), true)
		test:shouldBeEqual(qu2:hasMoreResults(), false)
		test:shouldBeEqual(qu3:hasMoreResults(), false)

        test:shouldBeEqual(next(qu:getData()) != nil, true)
        test:shouldBeEqual(next(qu1:getData()) != nil, true)
        test:shouldBeEqual(qu2:getData(), nil)
        test:shouldBeEqual(qu3:getData(), nil)

        test:shouldBeEqual(qu:getData()[1].a, 123)
        test:shouldBeEqual(qu1:getData()[1].b, "test")

		timer.Simple(0.1, function()
		    test:shouldBeEqual(qu:isRunning(), false)
			test:shouldBeEqual(qu1:isRunning(), false)
			test:shouldBeEqual(qu2:isRunning(), false)
		    test:shouldBeEqual(qu3:isRunning(), false)
			test:Complete()
		end)
	end
	transaction:start()
end)

TestFramework:RegisterTest("[Transaction] not break queries for queries started after the transaction", function(test)
	local db = TestFramework:ConnectToDatabase()
	local transaction = db:createTransaction()
	local qu = db:query("SELECT 123 as a")
	local errQuery = db:query("SELECT * * * * * *")
	local qu3 = db:query("SELECT 3 as a")
	transaction:addQuery(qu)
	transaction:addQuery(errQuery)
	transaction:start()

	function qu:onSuccess()
		test:shouldBeEqual(qu:error(), "")
        test:shouldBeEqual(next(qu:getData()) != nil, true)
        test:shouldBeEqual(qu:getData()[1].a, 123)
        test:shouldBeEqual(next(qu:getData()) != nil, true)
        test:shouldBeEqual(qu3:getData(), nil)
    end
    qu:start()

	function qu3:onSuccess()
		test:shouldBeEqual(qu3:error(), "")
        test:shouldBeEqual(next(qu3:getData()) != nil, true)
        test:shouldBeEqual(qu3:getData()[1].a, 3)
		test:Complete()
    end
    qu3:start()
end)